name: e_garage_proveedor
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  cloud_firestore: ^5.4.2
  dio: ^5.6.0
  firebase_auth: ^5.3.1
  firebase_core: ^3.6.0
  firebase_database: ^11.1.4
  flutter:
    sdk: flutter
  flutter_custom_tabs: ^2.1.0
  flutter_inappwebview: ^5.8.0
  flutter_map: ^4.0.0
  flutter_riverpod: ^2.5.1
  geolocator: ^13.0.1
  go_router: ^14.2.7
  google_nav_bar: ^5.0.6
  http: ^0.13.5
  intl: ^0.19.0
  latlong2: ^0.8.0
  local_auth: ^2.1.6
  mercadopago_sdk: ^1.1.3
  permission_handler: ^11.3.1
  riverpod: ^2.5.1
  shared_preferences: ^2.0.6
  table_calendar: ^3.0.0
  url_launcher: ^6.3.1
  flutter_bloc: ^8.1.6
  equatable: ^2.0.5
  firebase_messaging: ^15.1.4
  flutter_local_notifications: ^18.0.0
  geocoding: ^3.0.0
  
dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:

  uses-material-design: true
  assets:
    - assets/images/logo_proveedor.png

